### ISSUE TITLE
No open source license

### ISSUE THREAD

**Issue by nclinger** [kalbasit/arcanist-go#5]
Hi there,

There is no open source license on this repo.  Can I use this code as is?  Alternatively, I would also be willing to take over the repository if necessary.

Cheers,

Nate

**Comment by kalbasit** [comment]
@nclinger Good catch. This repo is licensed under Apache 2.0 license, the same license of Arcanist. Please open pull requests for your changes for now, and I'll consider giving you write access to the repository so you could maintain it moving forward.

**Comment by derekargueta** [comment]
@kalbasit seems this can be closed? Looks like you added a `LICENSE` file for Apache 2.0.
